#!/bin/bash


while true
do
    ping -i 1 -c 2 'www.google.com' > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        printf 'connection good :) '
        sleep 10
    else
        printf 'connection failed :( will attempt spoof'
        /usr/share/xfinitywifid/xfinity-spoofmac
        sleep 3
        python3 /usr/share/xfinitywifid/xfinity.py
        sleep 3
        ping -i 1 -c 1 'www.google.com' > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            printf 'connection fixed!! :)'
        fi
    fi
done
