#!/bin/bash


while true
do
    ping -i 1 -c 2 'www.google.com' > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        printf 'connection good :) '
        pkill 'firefox'
        sleep 3
    else
        osascript -e 'display notification "connection failed :( will attempt spoof" with title "xfinitywifi autospoofer"'
        /Applications/xfinitywifi-autospoof/kill_captive_network_assistant.sh &
        printf 'connection fail :( '
        /Applications/xfinitywifi-autospoof/xfinity.py
        sleep 1
        pkill -f "kill_captive_network_assistant"
        ping -i 1 -c 1 'www.google.com' > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            osascript -e 'display notification "connection fixed!! :)" with title "xfinitywifi autospoofer"'
        fi
    fi
done
